#!/bin/bash
echo "Installing dependencies..."
apt update && apt install python3 python3-dev python3-pip build-essential upx-ucl libssl-dev libffi-dev libvirt-dev curl zlib1g-dev -y

echo "Installing latest version of rust"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

echo "Activating rust"
export PATH="~/.cargo/bin:$PATH"
source $HOME/.cargo/env

rustup update

echo "Installing python dependencies"
cat >/etc/pip.conf <<EOL
[global]
extra-index-url=https://www.piwheels.org/simple
EOL

pip3 install -r requirements.txt
if [ $(uname -m) == "armv7l" ]; then
  echo "Installing armv7l pyinstaller for rpi3 compatibility"
  PYINSTALLER_COMPILE_BOOTLOADER=1 pip3 install "https://github.com/pyinstaller/pyinstaller/releases/download/v4.3/pyinstaller-4.3-py3-none-linux_armv7l.whl"
else
  echo "Installing pyinstaller"
  PYINSTALLER_COMPILE_BOOTLOADER=1 pip3 install pyinstaller
fi

hidden_imports="--hidden-import uvicorn \
  --hidden-import uvicorn.logging \
  --hidden-import uvicorn.loops \
  --hidden-import uvicorn.loops.auto \
  --hidden-import uvicorn.protocols \
  --hidden-import uvicorn.protocols.http \
  --hidden-import uvicorn.protocols.http.auto \
  --hidden-import uvicorn.protocols.websockets \
  --hidden-import uvicorn.protocols.websockets.auto \
  --hidden-import uvicorn.lifespan \
  --hidden-import uvicorn.lifespan.on
"

echo "Building wakeup server"
pyinstaller --onefile \
  $hidden_imports \
  --hidden-import wakeup \
  -n "wakeup.linux-$(uname -m)" \
  src/wakeup.py

echo "Building backend"
pyinstaller --onefile \
  $hidden_imports \
  --hidden-import main \
  -n "heimboard-backend.linux-$(uname -m)" \
  main.py

echo "Compiling successful"
