#!/bin/bash
echo "Installing dependencies..."
apt update && apt upgrade -y && apt install python3 python3-dev python3-pip git build-essential upx-ucl libssl-dev libffi-dev libvirt-dev curl zlib1g-dev -y
echo "Remove outdated version of python cryptography..."
apt remove --purge python3-cryptography -y

echo "Installing latest version of rust"
curl -O https://curl.se/ca/cacert.pem
curl --cacert cacert.pem --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

echo "Activating rust"
export PATH="~/.cargo/bin:$PATH"
source $HOME/.cargo/env

rustup update

echo "Installing python dependencies"
cat >/etc/pip.conf <<EOL
[global]
extra-index-url=https://www.piwheels.org/simple
EOL

pip3 install -r requirements.txt
if [ $(uname -m) == "armv7l" ]; then
  echo "Installing armv7l pyinstaller for rpi3 compatibility"
  PYINSTALLER_COMPILE_BOOTLOADER=1 pip3 install "https://github.com/pyinstaller/pyinstaller/releases/download/v4.3/pyinstaller-4.3-py3-none-linux_armv7l.whl"
else
  echo "Installing pyinstaller"
  git clone https://github.com/pyinstaller/pyinstaller
  cd pyinstaller
  git checkout v4.8
  cd bootloader && python3 ./waf distclean all
  cd ..
  python3 setup.py install
  cd ..
fi

make clean
echo "Building wakeup server"
mkdir out
make build-wakeup
cp dist/wakeup.linux* out/

make clean
echo "Building backend"
make build
cp dist/heimboard-backend.linux* out/
