name: hydrun CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Check changed files
    outputs:
      run_backend_build: ${{ steps.check_files.outputs.run_backend_build }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check files
        id: check_files
        run: |
          echo "=============== list changed files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of changed files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != "backend/"* ]]; then
              echo "This file is not under the directory 'backend/'."
              echo "::set-output name=run_backend_build::false"
              break
            else
              echo "::set-output name=run_backend_build::true"
            fi
          done < files.txt

  build-linux-backend:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.run_backend_build == 'true' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up hydrun
        run: |
          curl -L -o /tmp/hydrun https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)
          sudo install /tmp/hydrun /usr/local/bin
      - name: Build with hydrun
        working-directory: backend
        run: hydrun -a amd64,arm64,arm/v7 ./Hydrunfile
      - name: Build for Pi 3 with hydrun
        working-directory: backend
        run: hydrun -a arm/v7 -o balenalib/raspberrypi3 ./Hydrunfile pi3
      - name: Publish to GitHub releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            backend/out/*
